// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: intake.
// - Entity ID: 102019a1a09cfa17d17a4c602b2548b8624.
// - Entity Version: 102019a1fc9faf872c9a5575aef635e49c5.
// - Task ID: 68fde57de0de5532f2842f3f.
// - Task Root ID: 68fc6c4be40a2b28c321df89.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for IntakeModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface IntakeModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  item_id: string;
  qty: number;
  weight_kg?: number | null;
  source?: string | null;
  expiry_date?: string | null;
}

/**
 * ORM class for Intake entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class IntakeORM {
  private static instance: IntakeORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a1a09cfa17d17a4c602b2548b8624';
    this.entityName = 'intake';
    this.entityVersion = '102019a1fc9faf872c9a5575aef635e49c5';
    this.taskId = '68fde57de0de5532f2842f3f';
    this.taskRootId = '68fc6c4be40a2b28c321df89';
  }

  /**
   * Get singleton instance of IntakeORM
   */
  public static getInstance(): IntakeORM {
    if (!IntakeORM.instance) {
      IntakeORM.instance = new IntakeORM();
    }
    
    return IntakeORM.instance;
  }

  /**
   * Get all Intake records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllIntake(): Promise<IntakeModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Intake record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertIntake(data: IntakeModel[]): Promise<IntakeModel[]> {
    const structured = data.map((item) => CreateData(IntakeModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Intake records
   */
  async purgeAllIntake(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Intake records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listIntake(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[IntakeModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get intake by Id index
   * This function gets data by index.
   */
  async getIntakeById(
    id: string,
  ): Promise<IntakeModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) intake by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setIntakeById(
    id: string,
    data: IntakeModel
  ): Promise<IntakeModel[]> {
    const index = createIndexId(
      id
    );

    const values = IntakeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete intake by Id index
   */
  async deleteIntakeById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get intake by DataCreator index
   * This function gets data by index.
   */
  async getIntakeByDataCreator(
    data_creator: string,
  ): Promise<IntakeModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) intake by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setIntakeByDataCreator(
    data_creator: string,
    data: IntakeModel
  ): Promise<IntakeModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = IntakeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete intake by DataCreator index
   */
  async deleteIntakeByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get intake by DataUpdater index
   * This function gets data by index.
   */
  async getIntakeByDataUpdater(
    data_updater: string,
  ): Promise<IntakeModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) intake by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setIntakeByDataUpdater(
    data_updater: string,
    data: IntakeModel
  ): Promise<IntakeModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = IntakeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete intake by DataUpdater index
   */
  async deleteIntakeByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get intake by ItemId index
   * This function gets data by index.
   */
  async getIntakeByItemId(
    item_id: string,
  ): Promise<IntakeModel[]> {
    const index = createIndexItemId(
      item_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) intake by ItemId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setIntakeByItemId(
    item_id: string,
    data: IntakeModel
  ): Promise<IntakeModel[]> {
    const index = createIndexItemId(
      item_id
    );

    const values = IntakeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete intake by ItemId index
   */
  async deleteIntakeByItemId(
    item_id: string
  ): Promise<void> {
    const index = createIndexItemId(
      item_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get intake by ExpiryDate index
   * This function gets data by index.
   */
  async getIntakeByExpiryDate(
    expiry_date: string,
  ): Promise<IntakeModel[]> {
    const index = createIndexExpiryDate(
      expiry_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) intake by ExpiryDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setIntakeByExpiryDate(
    expiry_date: string,
    data: IntakeModel
  ): Promise<IntakeModel[]> {
    const index = createIndexExpiryDate(
      expiry_date
    );

    const values = IntakeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete intake by ExpiryDate index
   */
  async deleteIntakeByExpiryDate(
    expiry_date: string
  ): Promise<void> {
    const index = createIndexExpiryDate(
      expiry_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get intake by Source index
   * This function gets data by index.
   */
  async getIntakeBySource(
    source: string,
  ): Promise<IntakeModel[]> {
    const index = createIndexSource(
      source
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) intake by Source index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setIntakeBySource(
    source: string,
    data: IntakeModel
  ): Promise<IntakeModel[]> {
    const index = createIndexSource(
      source
    );

    const values = IntakeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete intake by Source index
   */
  async deleteIntakeBySource(
    source: string
  ): Promise<void> {
    const index = createIndexSource(
      source
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to IntakeModel data array
   */
  private resultToData(values: Data[]): IntakeModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return IntakeModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as IntakeModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized IntakeModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is IntakeModel => item !== null);
  }
}

/**
 * Convert IntakeModel data to Value array
 */
function IntakeModelToValues(data: IntakeModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'item_id', type: DataType.string, defaultValue: '' },
    { key: 'qty', type: DataType.number, defaultValue: 0 },
    { key: 'weight_kg', type: DataType.number, defaultValue: null },
    { key: 'source', type: DataType.string, defaultValue: null },
    { key: 'expiry_date', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof IntakeModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to IntakeModel data
 */
function IntakeModelFromValues(values: Value[]): IntakeModel {
  const data: Partial<IntakeModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'item_id':
        data.item_id = ParseValue(value, DataType.string) as string;
        break;
      case 'qty':
        data.qty = ParseValue(value, DataType.number) as number;
        break;
      case 'weight_kg':
        data.weight_kg = ParseValue(value, DataType.number) as number | null;
        break;
      case 'source':
        data.source = ParseValue(value, DataType.string) as string | null;
        break;
      case 'expiry_date':
        data.expiry_date = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as IntakeModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ItemId fields
 */
function createIndexItemId(
  item_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, item_id, 'item_id'),
  ];

  return {
    fields: ['item_id'],
    values
  };
}
/**
 * Create index for ExpiryDate fields
 */
function createIndexExpiryDate(
  expiry_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, expiry_date, 'expiry_date'),
  ];

  return {
    fields: ['expiry_date'],
    values
  };
}
/**
 * Create index for Source fields
 */
function createIndexSource(
  source: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, source, 'source'),
  ];

  return {
    fields: ['source'],
    values
  };
}

export default IntakeORM;