// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: item.
// - Entity ID: 102019a1a09cfa17aaea4f3be3287fd5250.
// - Entity Version: 102019a1fc9faf872c9a5575aef635e49c5.
// - Task ID: 68fde57de0de5532f2842f3f.
// - Task Root ID: 68fc6c4be40a2b28c321df89.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for ItemModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ItemModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  upc: string;
  name: string;
  brand?: string | null;
  category?: string | null;
  unit: string;
  image_url?: string | null;
  calories?: number | null;
  protein?: number | null;
  fat?: number | null;
  carbs?: number | null;
  fiber?: number | null;
  sugars?: number | null;
  sodium?: number | null;
  allergens?: string[] | null;
  dietary_tags?: string[] | null;
}

/**
 * ORM class for Item entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ItemORM {
  private static instance: ItemORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a1a09cfa17aaea4f3be3287fd5250';
    this.entityName = 'item';
    this.entityVersion = '102019a1fc9faf872c9a5575aef635e49c5';
    this.taskId = '68fde57de0de5532f2842f3f';
    this.taskRootId = '68fc6c4be40a2b28c321df89';
  }

  /**
   * Get singleton instance of ItemORM
   */
  public static getInstance(): ItemORM {
    if (!ItemORM.instance) {
      ItemORM.instance = new ItemORM();
    }
    
    return ItemORM.instance;
  }

  /**
   * Get all Item records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllItem(): Promise<ItemModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Item record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertItem(data: ItemModel[]): Promise<ItemModel[]> {
    const structured = data.map((item) => CreateData(ItemModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Item records
   */
  async purgeAllItem(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Item records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listItem(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ItemModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get item by Id index
   * This function gets data by index.
   */
  async getItemById(
    id: string,
  ): Promise<ItemModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) item by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setItemById(
    id: string,
    data: ItemModel
  ): Promise<ItemModel[]> {
    const index = createIndexId(
      id
    );

    const values = ItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete item by Id index
   */
  async deleteItemById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get item by DataCreator index
   * This function gets data by index.
   */
  async getItemByDataCreator(
    data_creator: string,
  ): Promise<ItemModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) item by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setItemByDataCreator(
    data_creator: string,
    data: ItemModel
  ): Promise<ItemModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete item by DataCreator index
   */
  async deleteItemByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get item by DataUpdater index
   * This function gets data by index.
   */
  async getItemByDataUpdater(
    data_updater: string,
  ): Promise<ItemModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) item by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setItemByDataUpdater(
    data_updater: string,
    data: ItemModel
  ): Promise<ItemModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete item by DataUpdater index
   */
  async deleteItemByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get item by Upc index
   * This function gets data by index.
   */
  async getItemByUpc(
    upc: string,
  ): Promise<ItemModel[]> {
    const index = createIndexUpc(
      upc
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) item by Upc index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setItemByUpc(
    upc: string,
    data: ItemModel
  ): Promise<ItemModel[]> {
    const index = createIndexUpc(
      upc
    );

    const values = ItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete item by Upc index
   */
  async deleteItemByUpc(
    upc: string
  ): Promise<void> {
    const index = createIndexUpc(
      upc
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get item by Name index
   * This function gets data by index.
   */
  async getItemByName(
    name: string,
  ): Promise<ItemModel[]> {
    const index = createIndexName(
      name
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) item by Name index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setItemByName(
    name: string,
    data: ItemModel
  ): Promise<ItemModel[]> {
    const index = createIndexName(
      name
    );

    const values = ItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete item by Name index
   */
  async deleteItemByName(
    name: string
  ): Promise<void> {
    const index = createIndexName(
      name
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get item by Category index
   * This function gets data by index.
   */
  async getItemByCategory(
    category: string,
  ): Promise<ItemModel[]> {
    const index = createIndexCategory(
      category
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) item by Category index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setItemByCategory(
    category: string,
    data: ItemModel
  ): Promise<ItemModel[]> {
    const index = createIndexCategory(
      category
    );

    const values = ItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete item by Category index
   */
  async deleteItemByCategory(
    category: string
  ): Promise<void> {
    const index = createIndexCategory(
      category
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ItemModel data array
   */
  private resultToData(values: Data[]): ItemModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ItemModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ItemModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ItemModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ItemModel => item !== null);
  }
}

/**
 * Convert ItemModel data to Value array
 */
function ItemModelToValues(data: ItemModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'upc', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'brand', type: DataType.string, defaultValue: null },
    { key: 'category', type: DataType.string, defaultValue: null },
    { key: 'unit', type: DataType.string, defaultValue: '' },
    { key: 'image_url', type: DataType.string, defaultValue: null },
    { key: 'calories', type: DataType.number, defaultValue: null },
    { key: 'protein', type: DataType.number, defaultValue: null },
    { key: 'fat', type: DataType.number, defaultValue: null },
    { key: 'carbs', type: DataType.number, defaultValue: null },
    { key: 'fiber', type: DataType.number, defaultValue: null },
    { key: 'sugars', type: DataType.number, defaultValue: null },
    { key: 'sodium', type: DataType.number, defaultValue: null },
    { key: 'allergens', type: DataType.array, defaultValue: null },
    { key: 'dietary_tags', type: DataType.array, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ItemModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ItemModel data
 */
function ItemModelFromValues(values: Value[]): ItemModel {
  const data: Partial<ItemModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'upc':
        data.upc = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'brand':
        data.brand = ParseValue(value, DataType.string) as string | null;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string | null;
        break;
      case 'unit':
        data.unit = ParseValue(value, DataType.string) as string;
        break;
      case 'image_url':
        data.image_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'calories':
        data.calories = ParseValue(value, DataType.number) as number | null;
        break;
      case 'protein':
        data.protein = ParseValue(value, DataType.number) as number | null;
        break;
      case 'fat':
        data.fat = ParseValue(value, DataType.number) as number | null;
        break;
      case 'carbs':
        data.carbs = ParseValue(value, DataType.number) as number | null;
        break;
      case 'fiber':
        data.fiber = ParseValue(value, DataType.number) as number | null;
        break;
      case 'sugars':
        data.sugars = ParseValue(value, DataType.number) as number | null;
        break;
      case 'sodium':
        data.sodium = ParseValue(value, DataType.number) as number | null;
        break;
      case 'allergens':
        data.allergens = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'dietary_tags':
        data.dietary_tags = ParseValue(value, DataType.array) as string[] | null;
        break;
    }
  }
  
  return data as ItemModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Upc fields
 */
function createIndexUpc(
  upc: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, upc, 'upc'),
  ];

  return {
    fields: ['upc'],
    values
  };
}
/**
 * Create index for Name fields
 */
function createIndexName(
  name: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, name, 'name'),
  ];

  return {
    fields: ['name'],
    values
  };
}
/**
 * Create index for Category fields
 */
function createIndexCategory(
  category: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, category, 'category'),
  ];

  return {
    fields: ['category'],
    values
  };
}

export default ItemORM;